version: '3'
services:
  app:
    image: placeholder_app_image
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/PLACEHOLDER_POSTGRES_DB_NAME
      SPRING_DATASOURCE_USERNAME: PLACEHOLDER_POSTGRES_USERNAME
      SPRING_DATASOURCE_PASSWORD: PLACEHOLDER_POSTGRES_PASSWORD

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: PLACEHOLDER_POSTGRES_DB_NAME
      POSTGRES_USER: PLACEHOLDER_POSTGRES_USERNAME
      POSTGRES_PASSWORD: PLACEHOLDER_POSTGRES_PASSWORD
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: